-- CREATE DATABASE WEB_BD_MANAGER_SYSTEM

CREATE TABLE CLIENTS_USERS_MANAGER
(
	COD_ID 			INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    USER_NAME		VARCHAR(200) NOT NULL						,
    EMAIL_CLIENT	VARCHAR(200) NOT NULL						,
    PASS_CLIENTE	VARCHAR(200) NOT NULL						,
    TEAM_COD		VARCHAR(200) 
)

DROP TABLE CLIENTS_USERS_MANAGER

SELECT * FROM CLIENTS_USERS_MANAGER

INSERT INTO CLIENTS_USERS_MANAGER (USER_NAME, EMAIL_CLIENT, PASS_CLIENTE) VALUES('adm','miguelhp373@gmail.com','1234')

